### ISSUE TITLE
kafka-source-connector worker tasks killing off over time

### ISSUE THREAD

**Issue by jare19** [GoogleCloudPlatform/pubsub#101]
I am still seeing an issue with the worker tasks killing off over time. Here is a snip of when it fails.

```
[2017-05-23 06:44:55,426] INFO Finished WorkerSourceTask{id=CPSConnector-2} commitOffsets successfully in 53 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:371)
[2017-05-23 06:44:55,426] ERROR Task CPSConnector-2 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at com.google.protobuf.AbstractMessageLite$Builder.checkForNullValues(AbstractMessageLite.java:379)
	at com.google.protobuf.AbstractMessageLite$Builder.addAll(AbstractMessageLite.java:366)
	at com.google.pubsub.v1.AcknowledgeRequest$Builder.addAllAckIds(AcknowledgeRequest.java:621)
	at com.google.pubsub.kafka.source.CloudPubSubSourceTask.ackMessages(CloudPubSubSourceTask.java:202)
	at com.google.pubsub.kafka.source.CloudPubSubSourceTask.poll(CloudPubSubSourceTask.java:108)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:162)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2017-05-23 06:44:55,427] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:142)
[2017-05-23 06:44:55,427] INFO Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer:689)
```

Also, if I hit the REST endpoint I still see "state":"FAILED" but status is HTTP/1.1 200 OK so I would be unable to monitor and restart the tasks that fail. as you can see below, there are a few worker tasks that are not active but the ones that are active are happy and healthy.

```
[2017-05-23 14:13:13,705] INFO Finished WorkerSourceTask{id=CPSConnector-0} commitOffsets successfully in 0 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:371)
[2017-05-23 14:13:20,047] INFO Finished WorkerSourceTask{id=CPSConnector-2} commitOffsets successfully in 0 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:371)
[2017-05-23 14:13:27,730] INFO Finished WorkerSourceTask{id=CPSConnector-4} commitOffsets successfully in 0 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:371)
[2017-05-23 14:13:29,672] INFO Finished WorkerSourceTask{id=CPSConnector-5} commitOffsets successfully in 1 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:371)
[2017-05-23 14:13:30,868] INFO Finished WorkerSourceTask{id=CPSConnector-6} commitOffsets successfully in 1 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:371)
[2017-05-23 14:13:31,264] INFO Finished WorkerSourceTask{id=CPSConnector-7} commitOffsets successfully in 1 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:371)
[2017-05-23 14:13:31,265] INFO Finished WorkerSourceTask{id=CPSConnector-9} commitOffsets successfully in 1 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:371)
[2017-05-23 14:13:43,706] INFO Finished WorkerSourceTask{id=CPSConnector-0} commitOffsets successfully in 0 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:371)
[2017-05-23 14:13:50,048] INFO Finished WorkerSourceTask{id=CPSConnector-2} commitOffsets successfully in 1 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:371)

kubectl exec -it tnd-connector-2484114934-4d9cv /bin/bash
<v:/opt/kafka_2.11-0.10.2.0# curl -i localhost:8083/connectors/CPSConnector/tasks/1/status
HTTP/1.1 200 OK
Date: Tue, 23 May 2017 14:14:49 GMT
Content-Type: application/json
Content-Length: 1326
Server: Jetty(9.2.15.v20160210)

{"state":"FAILED","trace":"java.util.ConcurrentModificationException\n\tat 
java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)\n\tat 
java.util.HashMap$KeyIterator.next(HashMap.java:1461)\n\tat 
com.google.protobuf.AbstractMessageLite$Builder.checkForNullValues(AbstractMessageLite.java:379)\n\tat 
com.google.protobuf.AbstractMessageLite$Builder.addAll(AbstractMessageLite.java:366)\n\tat 
com.google.pubsub.v1.AcknowledgeRequest$Builder.addAllAckIds(AcknowledgeRequest.java:621)\n\tat 
com.google.pubsub.kafka.source.CloudPubSubSourceTask.ackMessages(CloudPubSubSourceTask.java:202)\n\tat 
com.google.pubsub.kafka.source.CloudPubSubSourceTask.poll(CloudPubSubSourceTask.java:108)\n\tat 
org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:162)\n\tat 
org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)\n\tat 
org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)\n\tat 
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat 
java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat 
java.lang.Thread.run(Thread.java:748)\n","id":1,"worker_id":"REDACTED:8083"}root@tnd-connector-2484114934-4d9cv:/opt/kafka_2.11-0.10.2.0#
```

**Comment by kamalaboulhosn** [comment]
Is there any chance this is running an old version of the jar? I'm very surprised this could happen as the call to addAllAckIds is wrapped in a synchronized on the object on which iteration is being performed. Since it is a synchronized set, other operations like insertion should already be synchronized. It's hard to be sure if it is the old code or new code because the ackMessages line that throws the error (202) is the same line in both the code with and without the fix.

**Comment by jare19** [comment]
I switched to the new code yesterday, compiling on the container it is being run in.

**Comment by jare19** [comment]
I have decreased then volume of logs and as of now, things look to be better. will keep the thread updated as I check back later this evening on the worker tasks.

**Comment by jare19** [comment]
so far everything is looking good after bringing down the volume of logs, but it appears that a different exception is now taking a task offline, this is not happening often but still taking a task down and it is not recovering

```
[2017-05-24 03:41:52,439] ERROR Task CPSConnector-1 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
java.lang.RuntimeException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: The service was unable to fulfill your request. Please try again. [code=8a75]
	at com.google.pubsub.kafka.source.CloudPubSubSourceTask.poll(CloudPubSubSourceTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:162)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2017-05-24 03:41:52,443] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:142)
[2017-05-24 03:41:52,443] INFO Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer:689)
```
