### ISSUE TITLE
Struct message body does not support Map or Struct types.

### ISSUE THREAD

**Issue by justinnaldzin** [GoogleCloudPlatform/pubsub#151]
Using both JSON and AVRO I receive this `DataException`

**Struct message body does not support Map or Struct types.**

But as I understand, Struct and Map types should be converted to String.

https://github.com/GoogleCloudPlatform/pubsub/blob/d9d1765ac17f7d86f7b71ee20ca5320832b8b800/kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java#L218

Here is an example of the JSON:
```
{"schema":{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"}],"optional":false,"name":"mysql_instance.ticketmonster.customers.Key"},"payload":{"id":1001}}	{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"first_name"},{"type":"string","optional":false,"field":"last_name"},{"type":"string","optional":false,"field":"email"}],"optional":true,"name":"mysql_instance.ticketmonster.customers.Value","field":"before"},{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"first_name"},{"type":"string","optional":false,"field":"last_name"},{"type":"string","optional":false,"field":"email"}],"optional":true,"name":"mysql_instance.ticketmonster.customers.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":true,"field":"version"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"server_id"},{"type":"int64","optional":false,"field":"ts_sec"},{"type":"string","optional":true,"field":"gtid"},{"type":"string","optional":false,"field":"file"},{"type":"int64","optional":false,"field":"pos"},{"type":"int32","optional":false,"field":"row"},{"type":"boolean","optional":true,"default":false,"field":"snapshot"},{"type":"int64","optional":true,"field":"thread"},{"type":"string","optional":true,"field":"db"},{"type":"string","optional":true,"field":"table"}],"optional":false,"name":"io.debezium.connector.mysql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"}],"optional":false,"name":"mysql_instance.ticketmonster.customers.Envelope"},"payload":{"before":null,"after":{"id":1001,"first_name":"Sally","last_name":"Thomas","email":"sally.thomas@acme.com"},"source":{"version":"0.7.5","name":"mysql-instance","server_id":0,"ts_sec":0,"gtid":null,"file":"mysql-bin.000004","pos":6182,"row":0,"snapshot":true,"thread":null,"db":"ticketmonster","table":"customers"},"op":"c","ts_ms":1522334541441}}
```

```
2018-03-08 14:43:55,346 ERROR  ||  WorkerSinkTask{id=CPSConnector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted.   [org.apache.kafka.connect.runtime.WorkerSinkTask]
org.apache.kafka.connect.errors.DataException: Struct message body does not support Map or Struct types.
	at com.google.pubsub.kafka.sink.CloudPubSubSinkTask.handleValue(CloudPubSubSinkTask.java:218)
	at com.google.pubsub.kafka.sink.CloudPubSubSinkTask.put(CloudPubSubSinkTask.java:118)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-03-08 14:43:55,355 ERROR  ||  WorkerSinkTask{id=CPSConnector-0} Task threw an uncaught and unrecoverable exception   [org.apache.kafka.connect.runtime.WorkerTask]
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:517)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Struct message body does not support Map or Struct types.
	at com.google.pubsub.kafka.sink.CloudPubSubSinkTask.handleValue(CloudPubSubSinkTask.java:218)
	at com.google.pubsub.kafka.sink.CloudPubSubSinkTask.put(CloudPubSubSinkTask.java:118)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
	... 10 more
2018-03-08 14:43:55,355 ERROR  ||  WorkerSinkTask{id=CPSConnector-0} Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask]
```

**Comment by kamalaboulhosn** [comment]
There appears to be an issue in the connector where it does not handle optional fields correctly and where the error message is incorrect for field for which values are missing. I will fix that.

However, I'm not sure you want the converter to be interpreting your JSON or AVRO data. If you want the data that is published to Cloud Pub/Sub to be the same as the data that was in the messages stored in Kafka, then you don't want the connector to reinterpret this data (which is what is happening when it uses the Struct type). If you do not want the data to be interpreted, then I recommend setting `value.converter` to `org.apache.kafka.connect.converters.ByteArrayConverter` in the connector's config.
