### ISSUE TITLE
pubsub loadtest fails with timeout using cloudshell

### ISSUE THREAD

**Issue by stanzheng** [GoogleCloudPlatform/pubsub#160]
loadtest fails using google cloudshell to attempt to run test

Steps to reproduce: 

Using Cloud Shell
install go tool chain;  `sudo apt-get install golang`
Invoke command python run.py --project my-project --client_types=gcloud
_python

Expected:

Pub/Sub benchmarks 

Attached Stacktrace 

```
stanley_zheng@cloudreach-mars:~/pubsub/load-test-framework$ python run.py --project cloudreach-mars --client_types=gcloud
_python --test=throughput
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:536)
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.google.pubsub.flic:flic:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 184, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.release: debian
[INFO] os.detected.release.version: 9
[INFO] os.detected.release.like.debian: true
[INFO] os.detected.classifier: linux-x86_64
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building CompatibilityTesting 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- protobuf-maven-plugin:0.5.0:compile (default) @ flic ---
[INFO] Compiling 1 proto file(s) to /home/stanley_zheng/pubsub/load-test-framework/target/generated-sources/protobuf/java
[INFO]
[INFO] --- protobuf-maven-plugin:0.5.0:compile-custom (default) @ flic ---
[INFO] Compiling 1 proto file(s) to /home/stanley_zheng/pubsub/load-test-framework/target/generated-sources/protobuf/grpc-java
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ flic ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 15 resources
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ flic ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 24 source files to /home/stanley_zheng/pubsub/load-test-framework/target/classes
[WARNING] /home/stanley_zheng/pubsub/load-test-framework/target/generated-sources/protobuf/grpc-java/com/google/pubsub/flic/common/LoadtestGrpc.java: Some input files use or override a deprecated API.
[WARNING] /home/stanley_zheng/pubsub/load-test-framework/target/generated-sources/protobuf/grpc-java/com/google/pubsub/flic/common/LoadtestGrpc.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ flic ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/stanley_zheng/pubsub/load-test-framework/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ flic ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ flic ---
[INFO] Surefire report directory: /home/stanley_zheng/pubsub/load-test-framework/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.google.pubsub.flic.DriverTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.148 sec
Running com.google.pubsub.flic.output.SheetsServiceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.465 sec
Running com.google.pubsub.flic.common.LatencyDistributionTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.026 sec
Running com.google.pubsub.flic.controllers.ClientTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.066 sec

Results :

Tests run: 10, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ flic ---
[INFO] Building jar: /home/stanley_zheng/pubsub/load-test-framework/target/flic-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-shade-plugin:2.3:shade (driver) @ flic ---
[INFO] Including junit:junit:jar:4.12 in the shaded jar.
[INFO] Including org.hamcrest:hamcrest-core:jar:1.3 in the shaded jar.
[INFO] Including org.apache.kafka:kafka_2.11:jar:0.10.0.0 in the shaded jar.
[INFO] Including com.yammer.metrics:metrics-core:jar:2.2.0 in the shaded jar.
[INFO] Including org.scala-lang:scala-library:jar:2.11.8 in the shaded jar.
[INFO] Including org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.4 in the shaded jar.
[INFO] Including org.apache.kafka:kafka-clients:jar:0.10.0.0 in the shaded jar.
[INFO] Including net.jpountz.lz4:lz4:jar:1.3.0 in the shaded jar.
[INFO] Including org.xerial.snappy:snappy-java:jar:1.1.2.4 in the shaded jar.
[INFO] Including net.sf.jopt-simple:jopt-simple:jar:4.9 in the shaded jar.
[INFO] Including org.apache.zookeeper:zookeeper:jar:3.4.6 in the shaded jar.
[INFO] Including jline:jline:jar:0.9.94 in the shaded jar.
[INFO] Including io.netty:netty:jar:3.7.0.Final in the shaded jar.
[INFO] Including com.beust:jcommander:jar:1.48 in the shaded jar.
[INFO] Including com.google.cloud:google-cloud-pubsub:jar:0.24.0-beta in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:2.0.3.Final in the shaded jar.
[INFO] Including com.google.cloud:google-cloud-core:jar:1.6.0 in the shaded jar.
[INFO] Including joda-time:joda-time:jar:2.9.2 in the shaded jar.
[INFO] Including org.json:json:jar:20160810 in the shaded jar.
[INFO] Including com.google.http-client:google-http-client:jar:1.22.0 in the shaded jar.
[INFO] Including com.google.api:api-common:jar:1.1.0 in the shaded jar.
[INFO] Including com.google.api:gax:jar:1.8.1 in the shaded jar.
[INFO] Including com.google.auto.value:auto-value:jar:1.2 in the shaded jar.
[INFO] Including org.threeten:threetenbp:jar:1.3.3 in the shaded jar.
[INFO] Including com.google.auth:google-auth-library-oauth2-http:jar:0.8.0 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java-util:jar:3.3.1 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.7 in the shaded jar.
[INFO] Including com.google.api.grpc:proto-google-common-protos:jar:0.1.19 in the shaded jar.
[INFO] Including com.google.api.grpc:proto-google-iam-v1:jar:0.1.19 in the shaded jar.
[INFO] Including com.google.cloud:google-cloud-core-grpc:jar:1.6.0 in the shaded jar.
[INFO] Including com.google.auth:google-auth-library-credentials:jar:0.8.0 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java:jar:3.3.1 in the shaded jar.
[INFO] Including io.grpc:grpc-protobuf:jar:1.6.1 in the shaded jar.
[INFO] Including io.grpc:grpc-protobuf-lite:jar:1.6.1 in the shaded jar.
[INFO] Including io.grpc:grpc-context:jar:1.6.1 in the shaded jar.
[INFO] Including com.google.api:gax-grpc:jar:0.25.1 in the shaded jar.
[INFO] Including com.google.api.grpc:proto-google-cloud-pubsub-v1:jar:0.1.19 in the shaded jar.
[INFO] Including com.google.api.grpc:grpc-google-cloud-pubsub-v1:jar:0.1.19 in the shaded jar.
[INFO] Including io.grpc:grpc-netty:jar:1.6.1 in the shaded jar.
[INFO] Including io.grpc:grpc-core:jar:1.6.1 in the shaded jar.
[INFO] Including com.google.instrumentation:instrumentation-api:jar:0.4.3 in the shaded jar.
[INFO] Including io.opencensus:opencensus-api:jar:0.5.1 in the shaded jar.
[INFO] Including io.netty:netty-codec-http2:jar:4.1.14.Final in the shaded jar.
[INFO] Including io.netty:netty-codec-http:jar:4.1.14.Final in the shaded jar.
[INFO] Including io.netty:netty-codec:jar:4.1.14.Final in the shaded jar.
[INFO] Including io.netty:netty-handler:jar:4.1.14.Final in the shaded jar.
[INFO] Including io.netty:netty-buffer:jar:4.1.14.Final in the shaded jar.
[INFO] Including io.netty:netty-common:jar:4.1.14.Final in the shaded jar.
[INFO] Including io.netty:netty-handler-proxy:jar:4.1.14.Final in the shaded jar.
[INFO] Including io.netty:netty-transport:jar:4.1.14.Final in the shaded jar.
[INFO] Including io.netty:netty-resolver:jar:4.1.14.Final in the shaded jar.
[INFO] Including io.netty:netty-codec-socks:jar:4.1.14.Final in the shaded jar.
[INFO] Including io.grpc:grpc-stub:jar:1.6.1 in the shaded jar.
[INFO] Including io.grpc:grpc-auth:jar:1.6.1 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.4 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.4 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:22.0 in the shaded jar.
[INFO] Including com.google.code.findbugs:jsr305:jar:1.3.9 in the shaded jar.
[INFO] Including com.google.errorprone:error_prone_annotations:jar:2.0.18 in the shaded jar.
[INFO] Including com.google.j2objc:j2objc-annotations:jar:1.1 in the shaded jar.
[INFO] Including org.codehaus.mojo:animal-sniffer-annotations:jar:1.14 in the shaded jar.
[INFO] Including com.google.apis:google-api-services-pubsub:jar:v1-rev7-1.21.0 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.21 in the shaded jar.
[INFO] Including org.slf4j:slf4j-log4j12:jar:1.7.21 in the shaded jar.
[INFO] Including log4j:log4j:jar:1.2.17 in the shaded jar.
[INFO] Including com.google.apis:google-api-services-compute:jar:v1-rev125-1.22.0 in the shaded jar.
[INFO] Including com.google.apis:google-api-services-storage:jar:v1-rev85-1.22.0 in the shaded jar.
[INFO] Including com.google.apis:google-api-services-monitoring:jar:v3-rev9-1.22.0 in the shaded jar.
[INFO] Including com.google.api-client:google-api-client:jar:1.22.0 in the shaded jar.
[INFO] Including com.google.oauth-client:google-oauth-client:jar:1.22.0 in the shaded jar.
[INFO] Including com.google.http-client:google-http-client-jackson2:jar:1.22.0 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.1.3 in the shaded jar.
[INFO] Including com.google.guava:guava-jdk5:jar:17.0 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpcore:jar:4.2.5 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpclient:jar:4.2.5 in the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.1.1 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.6 in the shaded jar.
[INFO] Including com.google.apis:google-api-services-sheets:jar:v4-rev108-1.22.0 in the shaded jar.
[INFO] Including com.google.oauth-client:google-oauth-client-java6:jar:1.11.0-beta in the shaded jar.
[INFO] Including com.google.oauth-client:google-oauth-client-jetty:jar:1.22.0 in the shaded jar.
[INFO] Including org.mortbay.jetty:jetty:jar:6.1.26 in the shaded jar.
[INFO] Including org.mortbay.jetty:jetty-util:jar:6.1.26 in the shaded jar.
[INFO] Including org.mortbay.jetty:servlet-api:jar:2.5-20081211 in the shaded jar.
[INFO] Including com.101tec:zkclient:jar:0.7 in the shaded jar.
[WARNING] guava-22.0.jar, guava-jdk5-17.0.jar define 1340 overlappping classes:
[WARNING]   - com.google.common.cache.LocalCache$KeyIterator
[WARNING]   - com.google.common.collect.ImmutableMapValues$1
[WARNING]   - com.google.common.collect.WellBehavedMap$EntrySet$1
[WARNING]   - com.google.common.io.LineProcessor
[WARNING]   - com.google.common.util.concurrent.AbstractService$5
[WARNING]   - com.google.common.io.BaseEncoding$StandardBaseEncoding$2
[WARNING]   - com.google.common.reflect.ImmutableTypeToInstanceMap
[WARNING]   - com.google.common.io.ByteProcessor
[WARNING]   - com.google.common.math.package-info
[WARNING]   - com.google.common.util.concurrent.SimpleTimeLimiter
[WARNING]   - 1330 more...
[WARNING] maven-shade-plugin has detected that some .class files
[WARNING] are present in two or more JARs. When this happens, only
[WARNING] one single version of the class is copied in the uberjar.
[WARNING] Usually this is not harmful and you can skeep these
[WARNING] warnings, otherwise try to manually exclude artifacts
[WARNING] based on mvn dependency:tree -Ddetail=true and the above
[WARNING] output
[WARNING] See http://docs.codehaus.org/display/MAVENUSER/Shade+Plugin
[INFO] Replacing /home/stanley_zheng/pubsub/load-test-framework/target/driver.jar with /home/stanley_zheng/pubsub/load-test-framework/target/flic-1.0-SNAPSHOT-shaded.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.498 s
[INFO] Finished at: 2018-05-28T15:40:48-04:00
[INFO] Final Memory: 30M/106M
[INFO] ------------------------------------------------------------------------
java -jar target/driver.jar --project cloudreach-mars --cps_gcloud_python_publisher_count=1 --cps_gcloud_python_subscriber_count=1 --message_size=10000 --publish_batch_size=10 --request_rate=1000000000 --max_outstanding_requests=1600 --loadtest_duration=10m --burn_in_duration=2m --publish_batch_duration=50ms --num_cores_test
INFO-Topic already exists, reusing.
INFO-File cps-gcloud-java-publisher_startup_script.sh is current, reusing.
INFO-File kafka-publisher_startup_script.sh is current, reusing.
INFO-File cps-gcloud-ruby-subscriber_startup_script.sh is current, reusing.
INFO-File cps-gcloud-python-publisher_startup_script.sh is current, reusing.
INFO-File cps-gcloud-node-publisher_startup_script.sh is current, reusing.
INFO-File cps-gcloud-dotnet-subscriber_startup_script.sh is current, reusing.
INFO-File cps-gcloud-ruby-publisher_startup_script.sh is current, reusing.
INFO-File cps-gcloud-go-subscriber_startup_script.sh is current, reusing.
INFO-File kafka-subscriber_startup_script.sh is current, reusing.
INFO-File cps-gcloud-python-subscriber_startup_script.sh is current, reusing.
INFO-File cps-gcloud-go-publisher_startup_script.sh is current, reusing.
INFO-File cps-gcloud-node-subscriber_startup_script.sh is current, reusing.
INFO-File cps-gcloud-dotnet-publisher_startup_script.sh is current, reusing.
INFO-File cps-gcloud-java-subscriber_startup_script.sh is current, reusing.
INFO-File cps.zip is current, reusing.
INFO-File driver.jar is out of date, uploading new version.
INFO-Pub/Sub actions completed.
INFO-Kafka actions completed.
INFO-File driver.jar created.
INFO-File uploads completed.
INFO-Instance group creation completed.
INFO-Starting instances.
INFO-Successfully started all instances.
INFO-Connecting to 35.202.29.100:5000
INFO-Connecting to 35.232.176.112:5000
  

ERROR-Client failed to start 11 times, shutting down.
ERROR-Shutting down:
io.grpc.StatusRuntimeException: UNAVAILABLE
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:385)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:422)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:61)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:504)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:425)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:536)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:102)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /35.232.176.112:5000
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more
ERROR-Client failed to start 11 times, shutting down.
May 28, 2018 3:49:22 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
SEVERE: Got more than one input Future failure. Logging failures after the first
io.grpc.StatusRuntimeException: UNAVAILABLE
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:385)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:422)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:61)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:504)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:425)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:536)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:102)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /35.232.176.112:5000
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more

ERROR-An error occurred...
io.grpc.StatusRuntimeException: UNAVAILABLE
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:385)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:422)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:61)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:504)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:425)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:536)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:102)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /35.202.29.100:5000
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more
```

**Comment by kamalaboulhosn** [comment]
cloudshell instances do not allow outgoing connections to the GCE instances started for the load test (which need to be reached on port 5000). See https://cloud.google.com/shell/docs/limitations#outgoing_connections. Therefore, the cloud shell should not be used to initiate the load tests. I will update the documentation indicating the need to access this port.

**Comment by kamalaboulhosn** [comment]
The cloud shell no longer has this limitation, so it should be possible to run the load test from that environment now.
