### ISSUE TITLE
Many subscribers created and sometimes cleanup issues

### ISSUE THREAD

**Issue by holken1** [GoogleCloudPlatform/pubsub#211]
Hi. We're using this connector and generally it works well but from time to time I see SEVERE errors in the log like below. When looking into this issue I realize that the connector rather frequently (around 5-10 per 15 min interval) reports creating a new subscriber. I wonder if this is normal, and of course in particular I'm interested to know if some additional cleanup may be needed to avoid the SEVERE messages.

```[2019-09-26 10:38:32,304] INFO WorkerSourceTask{id=CPSElwatchConnector-0} Finished commitOffsets successfully in 13 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:496)
[2019-09-26 10:39:17,244] INFO Creating subscriber. (com.google.pubsub.kafka.source.CloudPubSubGRPCSubscriber:66)
Sep 26, 2019 10:39:17 AM io.grpc.internal.ManagedChannelImpl$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel io.grpc.internal.ManagedChannelImpl-91 for target pubsub.googleapis.com:443 was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and awaitTermination().```

**Comment by kamalaboulhosn** [comment]
Is this still happening? I wouldn't expect clients to be created extremely frequently. They should be created whenever another source task is created.

**Comment by nicodds** [comment]
I went in a similar problem. Apparently at random (probably depending on some co-ocurring condition), I see in the logs SEVERE errors like this:

```
Aug 21, 2020 9:32:13 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=49, target=pubsub.googleapis.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
        at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:314)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1600(InstantiatingGrpcChannelProvider.java:71)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:210)
        at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:217)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:200)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:156)
        at com.google.cloud.pubsub.v1.stub.GrpcSubscriberStub.create(GrpcSubscriberStub.java:272)
        at com.google.pubsub.kafka.source.CloudPubSubSourceConnector.verifySubscription(CloudPubSubSourceConnector.java:252)
        at com.google.pubsub.kafka.source.CloudPubSubSourceConnector.start(CloudPubSubSourceConnector.java:143)
        at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:110)
        at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:135)
        at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:195)
        at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:257)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:295)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:211)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)
```

In that case, the connector starts creating a lot of clients, until it completely consumes the hardware resources (on my laptop, it was using more than 10k threads).
