### ISSUE TITLE
Connector crash - `Could not initialize class io.netty.handler.ssl.OpenSsl`

### ISSUE THREAD

**Issue by martinhale** [GoogleCloudPlatform/pubsub#215]
I'm attempting to build & run the connector from the latest commit (0cce32c016800e8d535875d2dbc89aa5323b291b) but I'm having issues with the connector tasks crashing upon launch.

I'm building and embedding the `.jar` using the following `Dockerfile`:
```
FROM maven:3.6.3-jdk-8 AS builder

RUN cd tmp && \
  git clone --recursive https://github.com/GoogleCloudPlatform/pubsub && \
  cd pubsub/kafka-connector && \
  git checkout c8d7a0a9c3b4164d996592e3a5183c40f8fff424 && \
  mvn package

FROM confluentinc/cp-kafka-connect:5.3.1
COPY --from=builder /tmp/pubsub/kafka-connector/target/cps-kafka-connector.jar /usr/share/java/kafka/cps-kafka-connector.jar
```

When a connect task is launched I get the following error:
```
java.lang.NoClassDefFoundError: Could not initialize class io.netty.handler.ssl.OpenSsl
	at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:244)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:385)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:435)
	at com.google.pubsub.kafka.common.ConnectorUtils.getChannel(ConnectorUtils.java:55)
	at com.google.pubsub.kafka.source.CloudPubSubGRPCSubscriber.makeSubscriber(CloudPubSubGRPCSubscriber.java:67)
	at com.google.pubsub.kafka.source.CloudPubSubGRPCSubscriber.<init>(CloudPubSubGRPCSubscriber.java:47)
	at com.google.pubsub.kafka.source.CloudPubSubRoundRobinSubscriber.<init>(CloudPubSubRoundRobinSubscriber.java:39)
	at com.google.pubsub.kafka.source.CloudPubSubSourceTask.start(CloudPubSubSourceTask.java:131)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This was not occurring with the previous commit (c8d7a0a9c3b4164d996592e3a5183c40f8fff424). 

Does anyone have any ideas/pointers?

Thanks!

**Comment by nicodds** [comment]
I run in the same error. I suspect there is a problem with io.netty version. It is may be related to this merge https://github.com/GoogleCloudPlatform/pubsub/pull/213 ?

**Comment by kamalaboulhosn** [comment]
I am not able to reproduce the issue running Kafka 2.13 on a GCE instance. Can you please provide more details about the environment on which you are running the connector?

**Comment by nicodds** [comment]
That's the details:

Kafka:
2.12-2.4.1

JAVA: 
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~19.10-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

OS:
Ubuntu 19.10

**Comment by shardulsrivastava** [comment]
@nicodds  i had the same problem, i changed the version of `netty-tcnative-boringssl-static` from `2.0.8.Final` to `2.0.20.Final` and its working now.

**Comment by kamalaboulhosn** [comment]
Thanks, @shardulsrivastava. I have put in #220 to update the dependency.

**Comment by martinhale** [comment]
Thanks everyone 😄
