### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.google.pubsub.v1.ProjectTopicName

### ISSUE THREAD

**Issue by smit-aterlo** [GoogleCloudPlatform/pubsub#222]
I am getting the following error when I run my `connect-standalone.sh` and connector is not working in sending messages from pubsub to kafka or vice-versa 

```
[2020-05-21 16:17:45,269] ERROR WorkerSinkTask{id=CPSSinkConnector-9} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:186)
java.lang.NoClassDefFoundError: Could not initialize class com.google.pubsub.v1.ProjectTopicName
	at com.google.pubsub.kafka.sink.CloudPubSubSinkTask.createPublisher(CloudPubSubSinkTask.java:351)
	at com.google.pubsub.kafka.sink.CloudPubSubSinkTask.start(CloudPubSubSinkTask.java:143)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:305)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by kamalaboulhosn** [comment]
This looks like a case where maybe the wrong jar was used (one that didn't include the Pub/Sub client library). How did you make the connector available to your Connect instance?

**Comment by smit-aterlo** [comment]
I built one jar from this repo and copied it to kafka and provided the address in the `connect-standalone.properties` file

**Comment by smit-aterlo** [comment]
And the weird thing is it keeps going and starts running without panicking and the last error I am getting is 

```
[2020-05-21 17:33:11,180] INFO Creating connector CPSSourceConnector of type com.google.pubsub.kafka.source.CloudPubSubSourceConnector (org.apache.kafka.connect.runtime.Worker:251)
[2020-05-21 17:33:11,180] INFO Instantiated connector CPSSourceConnector with version 2.5.0 of type class com.google.pubsub.kafka.source.CloudPubSubSourceConnector (org.apache.kafka.connect.runtime.Worker:254)
[2020-05-21 17:33:11,183] ERROR WorkerConnector{id=CPSSourceConnector} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector:118)
java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at com.google.cloud.pubsub.v1.stub.SubscriberStubSettings.<clinit>(SubscriberStubSettings.java:115)
	at com.google.pubsub.kafka.source.CloudPubSubSourceConnector.verifySubscription(CloudPubSubSourceConnector.java:245)
	at com.google.pubsub.kafka.source.CloudPubSubSourceConnector.start(CloudPubSubSourceConnector.java:143)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:110)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:135)
	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:195)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:257)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:295)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:211)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:115)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 10 more
[2020-05-21 17:33:11,183] INFO Finished creating connector CPSSourceConnector (org.apache.kafka.connect.runtime.Worker:273)
[2020-05-21 17:33:11,183] INFO Skipping update of connector CPSSourceConnector since it is not running (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:327)
[2020-05-21 17:33:11,183] INFO Created connector CPSSourceConnector (org.apache.kafka.connect.cli.ConnectStandalone:112)

```

**Comment by matangans23** [comment]
I am having the same issue... were you able to resolve?

**Comment by smit-aterlo** [comment]
No I am still waiting for the help

**Comment by kamalaboulhosn** [comment]
I have not been able to reproduce this issue. What version of Kafka are you running? Do you have any other connectors loaded? What platform are you running on?

**Comment by matangans23** [comment]
I'm running the most recent release on my local machine (MacOS). No other connectors loaded

**Comment by matangans23** [comment]
I'm wondering if this might be an issue with the Maven dependencies associated with the imported PubSub APIs?

**Comment by kamalaboulhosn** [comment]
I am able to reproduce this issue using Kafka 2.5.0, but not with version 2.4.1. It makes we think something may have changed in the Kafka infrastructure. I tried recompiling against a more recent version of the connect API, but that did not help.

**Comment by ybudweiser** [comment]
I had to remove the guava exclusion here https://github.com/GoogleCloudPlatform/pubsub/blob/master/kafka-connector/pom.xml#L110

**Comment by kamalaboulhosn** [comment]
Indeed, that does seem to work, I have put in #225 to fix it. Thanks!
