### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by mehdihasan** [GoogleCloudPlatform/pubsub#256]
Hi, 

We have a Kafka installation which sources and sinks data from and to GCP pub-sub. We were using an older version of the CPS connector. Recently we have decided to use the latest one.

So we have downloaded your last alpha release version of the CPS connector, i.e. `v0.5-alpha`. 

We are facing an issue of increased thread consumption by the connector. Within 12 hours, it consumes 1K Threads. Whereas, the old version never consumes more than 30-60 threads over it's lifetime. 

Finally, after finishing consuming all the available threads, it stops functioning along with other Kafka Connect components. We start getting the following error after it consume all the available threads:

```
2021-01-19 09:19:48,669 ERROR WorkerSourceTask{id=CPSSourceConnectorV0-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-CPSSourceConnectorV0-0]
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1603)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:573)
	at com.google.api.gax.rpc.Watchdog.start(Watchdog.java:93)
	at com.google.api.gax.rpc.Watchdog.create(Watchdog.java:81)
	at com.google.api.gax.rpc.InstantiatingWatchdogProvider.getWatchdog(InstantiatingWatchdogProvider.java:113)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:188)
	at com.google.cloud.pubsub.v1.stub.GrpcSubscriberStub.create(GrpcSubscriberStub.java:272)
	at com.google.pubsub.kafka.source.CloudPubSubGRPCSubscriber.makeSubscriber(CloudPubSubGRPCSubscriber.java:78)
	at com.google.pubsub.kafka.source.CloudPubSubGRPCSubscriber.pull(CloudPubSubGRPCSubscriber.java:54)
	at com.google.pubsub.kafka.source.CloudPubSubRoundRobinSubscriber.pull(CloudPubSubRoundRobinSubscriber.java:46)
	at com.google.pubsub.kafka.source.CloudPubSubSourceTask.poll(CloudPubSubSourceTask.java:155)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:265)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-01-19 09:19:48,669 ERROR WorkerSourceTask{id=CPSSourceConnectorV0-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-CPSSourceConnectorV0-0]
```

**Comment by eazhilan-nagarajan** [comment]
Hello team,

Can someone help with an update on this issue? Did anyone else faced similar issues running the connector in Kubernetes?

**Comment by kamalaboulhosn** [comment]
@mehdihasan Do you know which version you were using before?

**Comment by mehdihasan** [comment]
@kamalaboulhosn thanks for your reply. Previously we have cloned the code from the master branch somewhere in early 2020.

**Comment by mehdihasan** [comment]
Hello @kamalaboulhosn / Guys,
1. Did you guys able to regenerate the issue?
2. Any plan for the root cause?

**Comment by mehdihasan** [comment]
Hi Again,

Which version of the connector you would suggest to use in production environment?

**Comment by mehdihasan** [comment]
Thanks @jinoobaek-qz. We were getting kind of the same and had captured that into prometheus grafana dashboard. 

![live_thread](https://user-images.githubusercontent.com/7582987/112015774-6852a280-8b2c-11eb-810b-8ad00a79b325.png)

You can see that the live thread count go beyond 4000. After it crossed that point we were start getting "Caused by: java.lang.OutOfMemoryError: unable to create native thread". In normal scenario (in fact for the previous version of the connector), the live thread count never goes beyond 70-80.

**Comment by mehdihasan** [comment]
I am not facing this issue with version **v0.8 Alpha**.
