### ISSUE TITLE
Seeing panic in the code to receive messages from pusub

### ISSUE THREAD

**Issue by rushit83** [GoogleCloudPlatform/pubsub#373]
While calling Receive method on Subscription, getting below panic 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16f0838]
goroutine 6948 [running]:
cloud.google.com/go/pubsub.(*pullStream).CloseSend.func1({0x0?, 0x0?})
cloud.google.com/go/pubsub@v1.38.0/pullstream.go:197 +0x18
cloud.google.com/go/pubsub.(*pullStream).call(0xc002936400, 0x37143c0, {0x0, 0x0, 0xc001527e58?})
cloud.google.com/go/pubsub@v1.38.0/pullstream.go:148 +0x144
cloud.google.com/go/pubsub.(*pullStream).CloseSend(0xc002936400)
cloud.google.com/go/pubsub@v1.38.0/pullstream.go:196 +0x2a
cloud.google.com/go/pubsub.(*messageIterator).sender.func1()
cloud.google.com/go/pubsub@v1.38.0/iterator.go:396 +0x25
cloud.google.com/go/pubsub.(*messageIterator).sender(0xc007852100)
cloud.google.com/go/pubsub@v1.38.0/iterator.go:479 +0x854
created by cloud.google.com/go/pubsub.newMessageIterator in goroutine 6944
cloud.google.com/go/pubsub@v1.38.0/iterator.go:152 +0x552 

Can someone help with why such panic could be raised by pubsub library while getting messages from pubsub ?

**Comment by kamalaboulhosn** [comment]
This GitHub repo is only for the load test framework and ordering keys prober. If you are running into issues for your own project or code, please see [Getting support](https://cloud.google.com/pubsub/docs/getting-support).
