### ISSUE TITLE
Flic does not compile on Cloud Shell

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/pubsub#43]
To reproduce: 
- Open Cloud Shell (a debian image)
- $sudo apt-get install openjdk-8-jre
- $export JAVA_HOME='/usr/lib/jvm/java-1.8.0-openjdk-amd64'
- python run.py --project=google.com:kir-learns-cloud --broker=10.142.0.7  --client_t
ype=vtk

Error message:
.....
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:03 min
[INFO] Finished at: 2017-01-09T17:20:03-05:00
[INFO] Final Memory: 27M/109M
[INFO] ------------------------------------------------------------------------
java -jar target/driver.jar --project google.com:kir-learns-cloud --cps_gcloud_java_publisher_count=1 --cps_gcloud_java_subscriber_count=1 --brok
er=10.142.0.7 --kafka_publisher_count=1 --kafka_subscriber_count=1 --message_size=1 --publish_batch_size=1 --request_rate=1 --max_outstanding_req
uests=10 --loadtest_duration=10m --burn_in_duration=2m --publish_batch_duration=1ms
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/pubsub/flic/Driver : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by mdietz94** [comment]
This is because 'java' here must be running Java 7, and not the one you want, major version 52 refers to Java 8.

Try doing:

/usr/bin/apt-get install -y openjdk-8-jre-headless

and don't export JAVA_HOME
