### ISSUE TITLE
stackdriver logs from pub/sub to kafka cps-source-connector

### ISSUE THREAD

**Issue by jare19** [GoogleCloudPlatform/pubsub#77]
*Kafka Version 2.11-0.10.1.0 (have also tried 2.11-0.10.2.0 with updates to the deps)*
I have hit a road block here, I have ran though the docs too many times to count and still am coming up short.  Hopefully someone can give me a pointer here so I can get this working.
## Issue
When running the cps-source-connector I get this error:
```
ERROR Task CPSConnector-3 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
org.apache.kafka.connect.errors.DataException: Conversion error: null value for field that is required and has no default value
	at org.apache.kafka.connect.json.JsonConverter.convertToJson(JsonConverter.java:556)
	at org.apache.kafka.connect.json.JsonConverter.convertToJsonWithEnvelope(JsonConverter.java:537)
	at org.apache.kafka.connect.json.JsonConverter.fromConnectData(JsonConverter.java:291)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:182)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:160)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
## Steps to Reproduce
1. Create pub/sub topic and subcription
2. Create stackdriver export (sink) with a basic log filter, for example: mine is just `gce_instance`
3.  In GCE instance install/start kafka via quickstart guide 
4. Follow README instructions from this kafka pubsub repo to get the source connector setup and configured.
5. create kafka topic
6.  run `bin/connect-standalone.sh config/connect-standalone.properties config/cps-source-connector.properties` to start connector
*properties file looks like this*
```
name=CPSConnector
connector.class=com.google.pubsub.kafka.source.CloudPubSubSourceConnector
tasks.max=10
cps.project=<actual project>
cps.subscription=<actual subscription>
kafka.topic=test2
```
7. Get error regarding null resource (see above)

## Troubleshooting
-verified export creds `export GOOGLE_APPLICATION_CREDENTIALS=<path to google svc acct json`
-issued glcoud command locally to pull subscription data successfully `gcloud beta pubsub subscriptions pull <subscription name>`
-combed through tons of code but made no progress (java noob here)
-Tons of permission checking in the google project and cross referencing the docs

**Comment by jare19** [comment]
@kamalaboulhosn  Unfortunatly, I am still getting this same error after a fresh pull and a fresh copy of your changed files.  Sadly, it didn't fix my issue.

**Comment by kamalaboulhosn** [comment]
@jare19 Is it possible that you had a copy of the old jar in your CLASSPATH that ended up being loaded? I am able to reproduce the issue without my patch, but if I patch it in, rebuild, replace the old cps-kafka-connector.jar with the newly-built one in target/, and run, the issue no longer appears.

**Comment by jare19** [comment]
@kamalaboulhosn Thankyou! I did find an old copy in my CLASSPATH, sorry about that mistake!  
Thank you so much for the update to this connector!
