### ISSUE TITLE
kafka -- CPS-source-connector dropping WorkerSourceTasks

### ISSUE THREAD

**Issue by jare19** [GoogleCloudPlatform/pubsub#97]
I keep randomly dropping workerSourceTasks (starts with 10) They will not restart unless I tell the REST endpoint to start it again. I have investigated and tried differrent settings all day yesterday with no luck keeping them up.
- Here is the output of a task failing after commiting the offsets
```
[2017-05-19 15:30:12,117] INFO Finished WorkerSourceTask{id=CPSConnector-4} commitOffsets successfully in 30 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:371)
[2017-05-19 15:30:12,117] ERROR Task CPSConnector-4 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at com.google.protobuf.AbstractMessageLite$Builder.checkForNullValues(AbstractMessageLite.java:379)
	at com.google.protobuf.AbstractMessageLite$Builder.addAll(AbstractMessageLite.java:366)
	at com.google.pubsub.v1.AcknowledgeRequest$Builder.addAllAckIds(AcknowledgeRequest.java:621)
	at com.google.pubsub.kafka.source.CloudPubSubSourceTask.ackMessages(CloudPubSubSourceTask.java:202)
	at com.google.pubsub.kafka.source.CloudPubSubSourceTask.poll(CloudPubSubSourceTask.java:108)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:162)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2017-05-19 15:30:12,173] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:142)
[2017-05-19 15:30:12,173] INFO Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer:689)
```
Also, I cannot keep a watch on the tasks because even though the state is 'failed' the header response is '200 OK'
```
HTTP/1.1 200 OK
Date: Fri, 19 May 2017 15:49:29 GMT
Content-Type: application/json
Content-Length: 1325
Server: Jetty(9.2.15.v20160210)

{
  "state": "FAILED",
  "trace": "java.util.ConcurrentModificationException\n\tat java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)\n\tat java.util.HashMap$KeyIterator.next(HashMap.java:1461)\n\tat com.google.protobuf.AbstractMessageLite$Builder.checkForNullValues(AbstractMessageLite.java:379)\n\tat com.google.protobuf.AbstractMessageLite$Builder.addAll(AbstractMessageLite.java:366)\n\tat com.google.pubsub.v1.AcknowledgeRequest$Builder.addAllAckIds(AcknowledgeRequest.java:621)\n\tat com.google.pubsub.kafka.source.CloudPubSubSourceTask.ackMessages(CloudPubSubSourceTask.java:202)\n\tat com.google.pubsub.kafka.source.CloudPubSubSourceTask.poll(CloudPubSubSourceTask.java:108)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:162)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:748)\n",
  "id": 4,
  "worker_id": "REDACTED:8083"
}
```

**Comment by kamalaboulhosn** [comment]
Should now be fixed!

**Comment by jare19** [comment]
Thank you for the quick turn-around, I will get this tested asap!

**Comment by jare19** [comment]
Unfortunately, after a fresh clone and recompile of the jar, I am getting the subscription does not exist for the project.

```
[2017-05-19 17:15:27,700] ERROR Error while starting connector CPSConnector (org.apache.kafka.connect.runtime.WorkerConnector:108)
org.apache.kafka.connect.errors.ConnectException: The subscription REDACTED does not exist for the projectREDACTED
	at com.google.pubsub.kafka.source.CloudPubSubSourceConnector.verifySubscription(CloudPubSubSourceConnector.java:201)
	at com.google.pubsub.kafka.source.CloudPubSubSourceConnector.start(CloudPubSubSourceConnector.java:116)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:100)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:125)
	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:182)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:183)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:251)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:177)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:93)
[2017-05-19 17:15:27,798] INFO Finished creating connector CPSConnector (org.apache.kafka.connect.runtime.Worker:194)
[2017-05-19 17:15:27,798] INFO Skipping reconfiguration of connector CPSConnector since it is not running (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:291)
[2017-05-19 17:15:27,799] INFO Created connector CPSConnector (org.apache.kafka.connect.cli.ConnectStandalone:90)
```

I typically would get this when there was a problem with authentication, all I did here was replace the jar in a working environment.

**Comment by kamalaboulhosn** [comment]
None of the changes made for this fix can affect the start or verifySubscription method, which hasn't changed in 10 months. Can you please verify that the subscription does indeed exist for the project? Perhaps a config file accidentally got updated on deployment?

**Comment by jare19** [comment]
I have just verified everything since I am running in a container in kubernetes, and everything was working just fine until I recompiled the jar today.  All values are still as expected in my container and permissions were just verified.  I did notice the pom was updated a few times recently, I am running 
ENV SCALA_VERSION="2.11" \
    KAFKA_VERSION="0.10.2.0"
And I remember having to update that manually in the pom before compiling, but notice that that is up to date now.... 
is there any deeper way for me to verify what step is failing here?

**Comment by jare19** [comment]
I just revered to the old .jar (built after your commit which fixed my null resource issue on April 7th https://github.com/GoogleCloudPlatform/pubsub/commit/e013cb32df8ea637403c30dc73dfbdfdde325fa3 #77 and #78 )  and now I am authenticated again and everything is happy and healthy --- ( besides the dropping of tasks that is)

**Comment by kamalaboulhosn** [comment]
I tried reproducing the issue, but I'm unable to. When I run on my Kafka instance with the latest code, everything works as expected. Could it be something in the environment? I recall with the last issue, there were some issues integrating fixes and it ended up being in the environment. Are there any other error messages prior to this message? 

If none of these things applies, it might be worth narrowing down the culprit change by checking out to the specific commits in the kafka connector repo and building from there to see when it broke.

**Comment by jare19** [comment]
So with the old fix, I had tried to update the repo and recomplile, but then ended up having to start fresh.  Today after your fix, I started with a fresh repo pull down recursive repo pull as it states in the readme, then did the build.  Uploaded that jar to my binrepo, rebuilt the container, and redployed the k8s pods.  Nothing had changed but that JAR.  I can share my docker file if you want but the only thing I am doing different than you, most likely, is not running my broker and zk on the same machine, it is purely running the connector in the container.  Oh and FWIW, the permission I have for my service account is role: roles/pubsub.editor NOT admin, but like I said, no issues other than the dropping of tasks with old .jar
Thank you so much for the help BTW, I have been banging my head on this one for the last few days.

**Comment by kamalaboulhosn** [comment]
Running Kafka and zookeeper on different machines would not matter. The error you are seeing is purely around the ability to read from the Cloud Pub/Sub subscription, which it claims does not exist. The interesting part wouldn't be the docker file; the interesting part would be your config file for your connector. Is there any way you could share that with me, including the project ID and subscription name?

**Comment by jare19** [comment]
```
name=CPSConnector
connector.class=com.google.pubsub.kafka.source.CloudPubSubSourceConnector
tasks.max=10
cps.project=xxx-xx-xxxx
cps.subscription=xxx_xxx_xxx
kafka.topic=xxx-xxx-xxx-xx-xxx-xx-xx-xx-xxx
cps.maxBatchSize=100
```
for real values you will have to share with me your google email and I can send it there, since my company has a NDA with google.

I did see you made another PR... would that change anything?  Should I try again?

**Comment by kamalaboulhosn** [comment]
You can email them to aboulhosn@google.com. The PR I added wouldn't affect this issue.
